- name: install repo
  shell: "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash"

- name: add variable
  shell: 'EXTERNAL_URL="http://gitlab.dexter.com.br"'

- name: instalar o GitLab-CE
  apt:
   name: "{{ item }}"
   state: present
  with_items:
   - gitlab-ce
  when: ansible_os_family == "Debian"
