- name: Download puppet-agent
  get_url:
   url: https://apt.puppetlabs.com/puppet5-release-xenial.deb
   dest: /tmp/puppet.deb
  when: ansible_os_family == "Debian"

- name: Instalar o repositorio
  apt:
   deb: /tmp/puppet.deb 
   update_cache: yes
  when: ansible_os_family == "Debian"

- name: Download repo puppet centos
  get_url:
   url: https://yum.puppet.com/puppet5/puppet-release-el-7.noarch.rpm
   dest: /tmp/puppet.rpm
  when: ansible_os_family == "RedHat"

- name: Instalar repo puppet centos
  yum:
   name: /tmp/puppet.rpm
   update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Instalando puppet-agent
  package:
   name: puppet-agent
   state: present
   update_cache: yes
