- name: Instalar o Apache e o PHP
   yum:
    name: "{{ item }}"
    state: present
   with_items:
    - httpd
   when: ansible_os_family == "RedHat"

- name: Verificando se o apache e esta habilitado
   service:
    name: "{{ item }}"
    state: started
   with_items:
    - httpd
   when: ansible_os_family == "RedHat"

- name: parando o firewalld
  service:
   name: firewalld
   state: stopped
  when: ansible_os_family == "RedHat"
