- name: Instalar o Apache e o PHP
   apt:
    name: "{{ item }}"
    state: present
   with_items:
    - apache2
   when: ansible_os_family == "Debian"

- name: Verificando se o apache e esta habilitado
   service:
    name: "{{ item }}"
    state: started
   with_items:
    - apache2
   when: ansible_os_family == "Debian"
