- name: excluindo a index padrao do apache
  command: test -f /var/www/html/index.html
  register: result

- name: excluindo o aquivo se existir
  file:
   path: /var/www/html/index.html
   state: absent
  when: result.rc == 0

- name: enviando arquivo index
  copy:
   src: ../files/index.html
   dest: /var/www/html/index.html
